"""Stage 5 (T5) — behaviour tests for sub-pixel refinement.

Ground truth is generated by shifting an image in the Fourier domain, which
applies an *exact* fractional translation rather than an interpolated
approximation. That matters: testing a sub-pixel estimator against a target
produced by bilinear interpolation would measure the interpolator, not the
estimator.
"""

import numpy as np
import pytest
import scipy.ndimage as ndi

from src import config, matcher
from src.types import Peak

TEMPLATE_SLICE = (slice(60, 124), slice(90, 154))
PEAK = Peak(col=90, row=60, score=1.0)


def band_limited_field(shape: tuple[int, int] = (256, 256), seed: int = 3) -> np.ndarray:
    """Return a smooth broadband field suitable for exact Fourier shifting."""
    rng = np.random.default_rng(seed)
    return ndi.gaussian_filter(rng.normal(0.0, 1.0, shape), 2.5).astype(np.float32)


def fourier_shift(image: np.ndarray, dy: float, dx: float) -> np.ndarray:
    """Translate an image by an exact fractional offset via its spectrum."""
    spectrum = np.fft.fft2(image)
    freq_row = np.fft.fftfreq(image.shape[0])[:, None]
    freq_col = np.fft.fftfreq(image.shape[1])[None, :]
    ramp = np.exp(-2j * np.pi * (freq_row * dy + freq_col * dx))
    return np.real(np.fft.ifft2(spectrum * ramp)).astype(np.float32)


def make_case(dy: float, dx: float, noise: float = 0.0, seed: int = 11):
    """Return ``(template, search)`` where the template sits at ``PEAK + (dx, dy)``."""
    field = band_limited_field()
    template = np.ascontiguousarray(field[TEMPLATE_SLICE])
    search = fourier_shift(field, dy, dx)
    if noise > 0.0:
        search = search + np.random.default_rng(seed).normal(0.0, noise, search.shape)
    return template, np.ascontiguousarray(search, dtype=np.float32)


# ---------------------------------------------------------------------------
# Accuracy — the primary routine
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "dy, dx",
    [(0.0, 0.0), (0.0, 0.3), (0.3, 0.0), (-0.25, 0.4), (0.45, -0.35), (0.5, 0.5), (-0.5, -0.5)],
)
def test_recovers_a_known_fractional_shift(dy, dx):
    template, search = make_case(dy, dx)
    refinement = matcher.refine_subpixel_detailed(template, search, PEAK)

    assert refinement.dx == pytest.approx(dx, abs=0.05)
    assert refinement.dy == pytest.approx(dy, abs=0.05)
    assert refinement.method == "phase_cross_correlation"


def test_zero_shift_gives_zero_offset():
    template, search = make_case(0.0, 0.0)
    refinement = matcher.refine_subpixel_detailed(template, search, PEAK)
    assert abs(refinement.dx) < 0.02
    assert abs(refinement.dy) < 0.02


def test_sign_convention_is_additive():
    """The offset must be *added* to the integer peak, not subtracted.

    A sign inversion here doubles the error instead of removing it, and is
    invisible whenever the true residual happens to be near zero.
    """
    dx, dy = 0.4, -0.3
    template, search = make_case(dy, dx)
    refinement = matcher.refine_subpixel_detailed(template, search, PEAK)

    naive_error = np.hypot(dx, dy)
    refined_error = np.hypot(dx - refinement.dx, dy - refinement.dy)
    assert refined_error < naive_error / 4


def test_refinement_beats_the_integer_peak_on_average():
    """The whole justification for Stage 5, measured over many offsets."""
    rng = np.random.default_rng(0)
    naive, refined = [], []
    for _ in range(25):
        dy, dx = rng.uniform(-0.5, 0.5, 2)
        template, search = make_case(dy, dx)
        refinement = matcher.refine_subpixel_detailed(template, search, PEAK)
        naive.append(np.hypot(dx, dy))
        refined.append(np.hypot(dx - refinement.dx, dy - refinement.dy))

    assert float(np.mean(refined)) < float(np.mean(naive)) / 10


def test_accuracy_is_within_the_tightest_tolerance():
    """Median residual must sit well inside the 0.5 px reporting tolerance."""
    rng = np.random.default_rng(1)
    errors = []
    for _ in range(25):
        dy, dx = rng.uniform(-0.5, 0.5, 2)
        template, search = make_case(dy, dx)
        refinement = matcher.refine_subpixel_detailed(template, search, PEAK)
        errors.append(np.hypot(dx - refinement.dx, dy - refinement.dy))

    assert float(np.median(errors)) < 0.05


# ---------------------------------------------------------------------------
# Windowing — the bias it removes
# ---------------------------------------------------------------------------


def test_windowing_removes_the_shrinkage_bias():
    """An unwindowed DFT systematically underestimates the shift.

    The transform treats its input as periodic, so mismatched patch edges leak
    broadband energy and pull the correlation peak toward zero. The refinement
    must not inherit that bias.
    """
    truths, estimates = [], []
    for dx in (0.1, 0.2, 0.3, 0.4, 0.5):
        template, search = make_case(0.0, dx)
        truths.append(dx)
        estimates.append(matcher.refine_subpixel_detailed(template, search, PEAK).dx)

    ratio = float(np.mean(np.array(estimates) / np.array(truths)))
    assert 0.95 < ratio < 1.05


# ---------------------------------------------------------------------------
# Robustness
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("noise", [0.02, 0.05, 0.1])
def test_survives_moderate_noise(noise):
    dy, dx = 0.35, -0.4
    template, search = make_case(dy, dx, noise=noise)
    refinement = matcher.refine_subpixel_detailed(template, search, PEAK)

    assert np.hypot(dx - refinement.dx, dy - refinement.dy) < 0.25


def test_registration_error_rises_with_noise():
    """The reported error must be informative, not decorative."""
    errors = []
    for noise in (0.0, 0.05, 0.2, 0.5):
        template, search = make_case(0.2, 0.2, noise=noise)
        errors.append(matcher.refine_subpixel_detailed(template, search, PEAK).error)

    assert errors == sorted(errors)


def test_wild_offsets_are_rejected_rather_than_applied():
    """A refinement larger than a pixel means the estimator latched onto noise.

    Applying it would turn a correct integer answer into a badly wrong sub-pixel
    one, so the offset is discarded and the result marked.
    """
    template = band_limited_field()[TEMPLATE_SLICE].copy()
    search = np.random.default_rng(9).normal(0, 1, (256, 256)).astype(np.float32)

    refinement = matcher.refine_subpixel_detailed(template, search, PEAK)
    assert abs(refinement.dx) <= 1.0
    assert abs(refinement.dy) <= 1.0


def test_constant_template_is_rejected():
    template = np.full((64, 64), 5.0, dtype=np.float32)
    search = band_limited_field()
    refinement = matcher.refine_subpixel_detailed(template, search, PEAK)
    assert refinement.method == "rejected"
    assert refinement.dx == 0.0
    assert refinement.dy == 0.0


def test_out_of_bounds_peak_is_rejected():
    template, search = make_case(0.0, 0.0)
    far = Peak(col=search.shape[1] - 2, row=search.shape[0] - 2, score=1.0)
    refinement = matcher.refine_subpixel_detailed(template, search, far)
    assert refinement.method == "rejected"


def test_is_deterministic():
    template, search = make_case(0.3, -0.2)
    first = matcher.refine_subpixel_detailed(template, search, PEAK)
    second = matcher.refine_subpixel_detailed(template, search, PEAK)
    assert (first.dx, first.dy) == (second.dx, second.dy)


def test_does_not_mutate_its_inputs():
    template, search = make_case(0.3, -0.2)
    before_template, before_search = template.copy(), search.copy()
    matcher.refine_subpixel_detailed(template, search, PEAK)
    np.testing.assert_array_equal(template, before_template)
    np.testing.assert_array_equal(search, before_search)


# ---------------------------------------------------------------------------
# The surface-upsampling fallback
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("dy, dx", [(0.0, 0.3), (0.3, 0.0), (-0.25, 0.4)])
def test_surface_upsampling_also_recovers_the_shift(dy, dx):
    template, search = make_case(dy, dx)
    surface = matcher.zncc_surface(template, search)
    offset_x, offset_y = matcher.refine_subpixel(surface, PEAK)

    assert offset_x == pytest.approx(dx, abs=0.15)
    assert offset_y == pytest.approx(dy, abs=0.15)


def test_both_routines_are_far_better_than_no_refinement():
    """Both are accurate; which is *more* accurate depends on the content.

    On band-limited noise the phase-correlation routine wins. On a strongly
    periodic field the surface-upsampling routine wins, because a lattice
    produces an unusually smooth, well-sampled correlation peak that interpolates
    very cleanly — the benchmark measures 0.004 px against 0.013 px there.

    So the assertion here is the one that actually holds across content: both
    routines cut the residual substantially against taking the integer peak.
    Declaring either universally superior would be over-claiming from one
    synthetic distribution, and the choice should be revisited on R1's realistic
    data rather than settled here.

    Measured on this fixture: integer 0.403 px, phase correlation 0.010 px
    (41x better), surface upsampling 0.087 px (4.6x better). The thresholds
    below are deliberately looser than those figures so the test tracks a real
    regression rather than fixture noise.
    """
    rng = np.random.default_rng(4)
    integer, primary, fallback = [], [], []
    for _ in range(20):
        dy, dx = rng.uniform(-0.5, 0.5, 2)
        template, search = make_case(dy, dx)
        surface = matcher.zncc_surface(template, search)

        pcc = matcher.refine_subpixel_detailed(template, search, PEAK)
        sx, sy = matcher.refine_subpixel(surface, PEAK)

        integer.append(np.hypot(dx, dy))
        primary.append(np.hypot(dx - pcc.dx, dy - pcc.dy))
        fallback.append(np.hypot(dx - sx, dy - sy))

    assert float(np.median(primary)) < float(np.median(integer)) / 10
    assert float(np.median(fallback)) < float(np.median(integer)) / 3


def test_falls_back_when_the_primary_is_rejected():
    template = np.full((64, 64), 5.0, dtype=np.float32)
    search = band_limited_field()
    surface = np.zeros((100, 100), dtype=np.float32)
    surface[60, 90] = 1.0

    refinement = matcher.refine_subpixel_detailed(template, search, PEAK, surface=surface)
    assert refinement.method in {"surface_upsampling", "rejected"}


def test_upsampled_patch_reproduces_its_samples():
    """Sanity check on the interpolator: at integer offsets it must be exact."""
    patch = np.array(
        [[0.1, 0.2, 0.1], [0.2, 1.0, 0.3], [0.1, 0.3, 0.2]],
        dtype=np.float32,
    )
    values, offsets = matcher._upsampled_patch(patch, upsample=1, span=1.0)
    np.testing.assert_allclose(values, patch, atol=1e-6)
    np.testing.assert_allclose(offsets, [-1.0, 0.0, 1.0], atol=1e-12)


# ---------------------------------------------------------------------------
# Interface preservation
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("upsample", [0, -1])
def test_all_entry_points_reject_invalid_upsample(upsample):
    template, search = make_case(0.0, 0.0)
    surface = np.zeros((100, 100), dtype=np.float32)

    with pytest.raises(ValueError, match="upsample"):
        matcher.refine_subpixel(surface, PEAK, upsample=upsample)
    with pytest.raises(ValueError, match="upsample"):
        matcher.refine_subpixel_crop(template, search, PEAK, upsample=upsample)
    with pytest.raises(ValueError, match="upsample"):
        matcher.refine_subpixel_detailed(template, search, PEAK, upsample=upsample)


def test_tuple_entry_points_agree_with_the_detailed_one():
    template, search = make_case(0.3, -0.2)
    detailed = matcher.refine_subpixel_detailed(template, search, PEAK)
    assert matcher.refine_subpixel_crop(template, search, PEAK) == (detailed.dx, detailed.dy)


def test_default_upsample_comes_from_config():
    template, search = make_case(0.25, 0.25)
    explicit = matcher.refine_subpixel_crop(
        template, search, PEAK, upsample=config.DEFAULT_UPSAMPLE
    )
    assert matcher.refine_subpixel_crop(template, search, PEAK) == explicit


# ---------------------------------------------------------------------------
# Integration with localize()
# ---------------------------------------------------------------------------


def test_localize_reports_subpixel_diagnostics(two_scale_pair):
    from src.localize import localize

    reference, search, _ = two_scale_pair
    result = localize(search, reference, mode="fast")

    assert result.diagnostics.subpixel_method == "phase_cross_correlation"
    assert np.isfinite(result.diagnostics.subpixel_error)
    assert 0.0 <= result.diagnostics.subpixel_error <= 1.0


def test_localize_produces_non_integer_coordinates(two_scale_pair):
    """Sub-pixel output must actually be sub-pixel, not silently rounded."""
    from src.localize import localize

    reference, search, _ = two_scale_pair
    shifted = fourier_shift(search, 0.3, -0.4)
    result = localize(shifted, reference, mode="fast")

    assert (result.x % 1.0, result.y % 1.0) != (0.5, 0.5)
